# ============================================================
# HOURLY SHARP EXTRACTION FROM JSOC (MODIFIED FROM YOUR STYLE)
# ============================================================

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:

!pip install -q drms pandas tqdm

import os
import re
import time
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
import drms

In [ ]:
# ============================================================
# 0. PATHS
# ============================================================
AR_MAIN_BASE = "/content/drive/MyDrive/AR_Stratified"
OUT_BASE = f"{AR_MAIN_BASE}/HMI_SHARP_HOURLY"
os.makedirs(OUT_BASE, exist_ok=True)

# JSOC client
c = drms.Client()

print("DRMS client ready.")
print("Output folder:", OUT_BASE)

DRMS client ready.
Output folder: /content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY

In [ ]:
# ============================================================
# 1. KEYS TO EXTRACT
# ============================================================
SHARP_KEYS = [
    "T_REC",
    "HARPNUM",
    "NOAA_ARS",
    "QUALITY",
    "MEANGBZ",
    "MEANGAM",
    "MEANGBT",
    "MEANGBH",
    "MEANJZD",
    "TOTUSJZ",
    "MEANALP",
    "MEANJZH",
    "ABSNJZH",
    "SAVNCPP",
    "MEANSHR",
    "SHRGT45",
    "R_VALUE",
    "USFLUX",
    "TOTPOT",
    "TOTUSJH",
    "AREA_ACR",
    "MEANPOT",
    "LON_MIN",
    "LON_MAX",
    "LAT_MIN",
    "LAT_MAX"
]

print("Total keys:", len(SHARP_KEYS))

Total keys: 26

In [ ]:
# ============================================================
# 2. HELPERS
# ============================================================
def extract_primary_ar(x):
    if pd.isna(x):
        return np.nan
    s = str(x).strip()
    if s.lower() in ["nan", "none", "missing", ""]:
        return np.nan
    m = re.search(r"\d+", s)
    return int(m.group()) if m else np.nan


def parse_trec(df):
    df = df.copy()
    df["T_REC"] = df["T_REC"].astype(str).str.strip()
    df["T_REC_dt"] = pd.to_datetime(
        df["T_REC"],
        format="%Y.%m.%d_%H:%M:%S_TAI",
        errors="coerce"
    )
    df["year"] = df["T_REC_dt"].dt.year
    return df


def clean_sharp_df(df):
    df = df.copy()
    df.columns = df.columns.str.strip()

    df = parse_trec(df)

    if "NOAA_ARS" in df.columns:
        df["NOAA_AR"] = df["NOAA_ARS"].apply(extract_primary_ar).astype("Int64")
    else:
        df["NOAA_AR"] = pd.Series([pd.NA] * len(df), dtype="Int64")

    # numeric conversion
    for col in df.columns:
        if col not in ["T_REC", "NOAA_ARS", "T_REC_dt"]:
            try:
                df[col] = pd.to_numeric(df[col], errors="ignore")
            except Exception:
                pass

    # drop bad timestamps
    df = df.dropna(subset=["T_REC_dt"]).copy()

    # quality filter if present
    if "QUALITY" in df.columns:
        df["QUALITY"] = pd.to_numeric(df["QUALITY"], errors="coerce")
        df = df[df["QUALITY"] == 0].copy()

    # deduplicate at HARPNUM + time
    subset_cols = [c for c in ["HARPNUM", "T_REC_dt"] if c in df.columns]
    if subset_cols:
        df = df.drop_duplicates(subset=subset_cols, keep="first")

    df = df.sort_values(["T_REC_dt", "HARPNUM"] if "HARPNUM" in df.columns else ["T_REC_dt"]).reset_index(drop=True)
    return df


def build_candidate_queries(start_ts, n_days):
    """
    Build a few syntax variants in case JSOC is picky.
    The important bit is:
        hmi.sharp_cea_720s[][TIME_FILTER]
    because HARPNUM is the first prime key and T_REC is the second.
    """
    s1 = start_ts.strftime("%Y.%m.%d_%H:%M:%S_TAI")
    s2 = start_ts.strftime("%Y.%m.%d_%H:%M_TAI")

    candidates = [
        f"hmi.sharp_cea_720s[][{s1}/{n_days}d@1h]",
        f"hmi.sharp_cea_720s[][{s2}/{n_days}d@1h]",
        f"hmi.sharp_cea_720s[][{s1}/{n_days}d]",
        f"hmi.sharp_cea_720s[][{s2}/{n_days}d]",
    ]
    return candidates


def query_chunk(start_ts, n_days, keys):
    """
    Try multiple query syntaxes and return the first successful DataFrame.
    """
    candidates = build_candidate_queries(start_ts, n_days)

    last_err = None
    for ds in candidates:
        try:
            print("Trying query:", ds)
            df = c.query(ds, key=",".join(keys))
            if df is not None and len(df) > 0:
                print("Success with:", ds)
                return df, ds
        except Exception as e:
            last_err = e
            print("Failed:", e)

    raise RuntimeError(f"All query variants failed for chunk starting {start_ts}. Last error: {last_err}")

In [ ]:

# ============================================================
# 3. TEST ONE SMALL QUERY FIRST
# ============================================================
test_start = pd.Timestamp("2014-01-01 00:00:00")
test_days = 1

test_df, test_ds = query_chunk(test_start, test_days, SHARP_KEYS)
print("\nTest query worked.")
print("Query used:", test_ds)
print("Returned shape:", test_df.shape)
display(test_df.head())

Trying query: hmi.sharp_cea_720s[][2014.01.01_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2014.01.01_00:00:00_TAI/1d@1h]

Test query worked.
Query used: hmi.sharp_cea_720s[][2014.01.01_00:00:00_TAI/1d@1h]
Returned shape: (235, 26)

,T_REC,HARPNUM,NOAA_ARS,QUALITY,MEANGBZ,MEANGAM,MEANGBT,MEANGBH,MEANJZD,TOTUSJZ,...,R_VALUE,USFLUX,TOTPOT,TOTUSJH,AREA_ACR,MEANPOT,LON_MIN,LON_MAX,LAT_MIN,LAT_MAX
0,2014.01.01_00:00:00_TAI,3520,"11931,11934,11935,11939",0,63.758,30.447,59.207,28.449,-0.239725,1.545143e+13,...,4.602,2.425337e+22,1.239458e+23,782.811,617.493835,2609.887,67.791039,90.513145,-22.551620,-11.495181
1,2014.01.01_01:00:00_TAI,3520,"11931,11934,11935,11939",0,63.822,29.900,58.984,27.470,-0.123619,1.432997e+13,...,4.629,2.290200e+22,1.106118e+23,722.082,587.512512,2428.895,68.348007,90.624245,-22.497293,-11.414536
2,2014.01.01_02:00:00_TAI,3520,"11931,11934,11935,11939",0,60.254,29.565,56.988,27.426,-0.178864,1.302870e+13,...,4.764,2.217570e+22,1.028660e+23,675.369,529.723206,2369.288,68.884651,90.498116,-22.410145,-11.411620
3,2014.01.01_03:00:00_TAI,3520,"11931,11934,11935,11939",0,58.173,29.099,55.478,26.581,-0.183216,1.231356e+13,...,4.695,2.158969e+22,9.661745e+22,659.351,466.931671,2317.302,69.455490,90.584892,-22.276407,-11.403701
4,2014.01.01_04:00:00_TAI,3520,"11931,11934,11935,11939",0,65.344,28.754,60.128,27.523,-0.101684,1.271466e+13,...,4.656,2.077681e+22,8.753201e+22,655.775,396.770172,2206.799,70.044754,90.724327,-22.210768,-11.431168

In [ ]:
# ============================================================
# 4. YEARLY HOURLY EXTRACTION IN 7-DAY CHUNKS
# ============================================================
def fetch_hourly_sharp_year(year, out_dir=OUT_BASE, chunk_days=7, pause_sec=1):
    start_year = pd.Timestamp(f"{year}-01-01 00:00:00")
    end_year = pd.Timestamp(f"{year+1}-01-01 00:00:00")

    print(f"\n{'='*70}")
    print(f"FETCHING YEAR {year}")
    print(f"{'='*70}")

    chunks = []
    chunk_start = start_year

    while chunk_start < end_year:
        chunk_end = min(chunk_start + pd.Timedelta(days=chunk_days), end_year)
        n_days = int((chunk_end - chunk_start).total_seconds() / 86400)

        # safety for final small chunk
        if n_days < 1:
            break

        try:
            df_chunk, ds_used = query_chunk(chunk_start, n_days, SHARP_KEYS)

            if df_chunk is not None and len(df_chunk) > 0:
                df_chunk = clean_sharp_df(df_chunk)
                chunks.append(df_chunk)
                print(f"Chunk saved in memory: {chunk_start} -> rows={len(df_chunk)}")
            else:
                print(f"No rows for chunk starting {chunk_start}")

        except Exception as e:
            print(f"Chunk failed for {chunk_start}: {e}")

        chunk_start = chunk_end
        time.sleep(pause_sec)

    if len(chunks) == 0:
        print(f"No data collected for year {year}")
        return None

    year_df = pd.concat(chunks, ignore_index=True)

    # keep only target year after parsing
    year_df = year_df[year_df["year"] == year].copy()

    # deduplicate again after concat
    dedup_cols = [c for c in ["HARPNUM", "T_REC_dt"] if c in year_df.columns]
    if dedup_cols:
        year_df = year_df.drop_duplicates(subset=dedup_cols, keep="first")

    year_df = year_df.sort_values(["HARPNUM", "T_REC_dt"]).reset_index(drop=True)

    out_path = os.path.join(out_dir, f"hmi_hourly_sharp_{year}.csv")
    year_df.to_csv(out_path, index=False)

    print(f"\nSaved year {year} to:")
    print(out_path)
    print("Final shape:", year_df.shape)

    return year_df

In [ ]:
df_2014 = fetch_hourly_sharp_year(2014, chunk_days=7)

if df_2014 is not None:
    print(df_2014.head())
    print("\nColumns:")
    print(df_2014.columns.tolist())

    print("\nGrouped cadence check within HARPNUM:")
    print(
        df_2014.sort_values(["HARPNUM", "T_REC_dt"])
               .groupby("HARPNUM")["T_REC_dt"]
               .diff()
               .value_counts()
               .head(20)
    )

======================================================================
FETCHING YEAR 2014
======================================================================
Trying query: hmi.sharp_cea_720s[][2014.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-01-01 00:00:00 -> rows=1840

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-01-08 00:00:00 -> rows=2455

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-01-15 00:00:00 -> rows=1454

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-01-22 00:00:00 -> rows=1233

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-01-29 00:00:00 -> rows=1014

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-02-05 00:00:00 -> rows=1986

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-02-12 00:00:00 -> rows=1472

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-02-19 00:00:00 -> rows=1574

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-02-26 00:00:00 -> rows=1270

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-03-05 00:00:00 -> rows=1523

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-03-12 00:00:00 -> rows=1314

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-03-19 00:00:00 -> rows=1844

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-03-26 00:00:00 -> rows=2216

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-04-02 00:00:00 -> rows=1836

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-04-09 00:00:00 -> rows=1674

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-04-16 00:00:00 -> rows=2306

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.04.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.04.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-04-23 00:00:00 -> rows=2543

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-04-30 00:00:00 -> rows=1898

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-05-07 00:00:00 -> rows=1831

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-05-14 00:00:00 -> rows=1797

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-05-21 00:00:00 -> rows=1210

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-05-28 00:00:00 -> rows=1321

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-06-04 00:00:00 -> rows=1347

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-06-11 00:00:00 -> rows=1984

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-06-18 00:00:00 -> rows=1328

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-06-25 00:00:00 -> rows=1250

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-07-02 00:00:00 -> rows=1774

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-07-09 00:00:00 -> rows=1591

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-07-16 00:00:00 -> rows=1092

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-07-23 00:00:00 -> rows=1295

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-07-30 00:00:00 -> rows=1797

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-08-06 00:00:00 -> rows=1402

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-08-13 00:00:00 -> rows=1386

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-08-20 00:00:00 -> rows=1042

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-08-27 00:00:00 -> rows=1640

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-09-03 00:00:00 -> rows=1935

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-09-10 00:00:00 -> rows=1710

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-09-17 00:00:00 -> rows=1631

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-09-24 00:00:00 -> rows=1870

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-10-01 00:00:00 -> rows=1665

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-10-08 00:00:00 -> rows=1358

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-10-15 00:00:00 -> rows=1929

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-10-22 00:00:00 -> rows=1612

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-10-29 00:00:00 -> rows=2356

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-11-05 00:00:00 -> rows=1942

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-11-12 00:00:00 -> rows=1729

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-11-19 00:00:00 -> rows=1429

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-11-26 00:00:00 -> rows=1937

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-12-03 00:00:00 -> rows=1910

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-12-10 00:00:00 -> rows=1758

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-12-17 00:00:00 -> rows=1843

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-12-24 00:00:00 -> rows=2622

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2014.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2014-12-31 00:00:00 -> rows=288

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2014 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2014.csv
Final shape: (88063, 29)
                     T_REC  HARPNUM                 NOAA_ARS  QUALITY  \
0  2014.01.01_00:00:00_TAI     3520  11931,11934,11935,11939        0
1  2014.01.01_01:00:00_TAI     3520  11931,11934,11935,11939        0
2  2014.01.01_02:00:00_TAI     3520  11931,11934,11935,11939        0
3  2014.01.01_03:00:00_TAI     3520  11931,11934,11935,11939        0
4  2014.01.01_04:00:00_TAI     3520  11931,11934,11935,11939        0

   MEANGBZ  MEANGAM  MEANGBT  MEANGBH   MEANJZD       TOTUSJZ  ...  TOTUSJH  \
0   63.758   30.447   59.207   28.449 -0.239725  1.545143e+13  ...  782.811
1   63.822   29.900   58.984   27.470 -0.123619  1.432997e+13  ...  722.082
2   60.254   29.565   56.988   27.426 -0.178864  1.302870e+13  ...  675.369
3   58.173   29.099   55.478   26.581 -0.183216  1.231356e+13  ...  659.351
4   65.344   28.754   60.128   27.523 -0.101684  1.271466e+13  ...  655.775

     AREA_ACR   MEANPOT    LON_MIN    LON_MAX    LAT_MIN    LAT_MAX  \
0  617.493835  2609.887  67.791039  90.513145 -22.551620 -11.495181
1  587.512512  2428.895  68.348007  90.624245 -22.497293 -11.414536
2  529.723206  2369.288  68.884651  90.498116 -22.410145 -11.411620
3  466.931671  2317.302  69.455490  90.584892 -22.276407 -11.403701
4  396.770172  2206.799  70.044754  90.724327 -22.210768 -11.431168

             T_REC_dt  year  NOAA_AR
0 2014-01-01 00:00:00  2014    11931
1 2014-01-01 01:00:00  2014    11931
2 2014-01-01 02:00:00  2014    11931
3 2014-01-01 03:00:00  2014    11931
4 2014-01-01 04:00:00  2014    11931

[5 rows x 29 columns]

Columns:
['T_REC', 'HARPNUM', 'NOAA_ARS', 'QUALITY', 'MEANGBZ', 'MEANGAM', 'MEANGBT', 'MEANGBH', 'MEANJZD', 'TOTUSJZ', 'MEANALP', 'MEANJZH', 'ABSNJZH', 'SAVNCPP', 'MEANSHR', 'SHRGT45', 'R_VALUE', 'USFLUX', 'TOTPOT', 'TOTUSJH', 'AREA_ACR', 'MEANPOT', 'LON_MIN', 'LON_MAX', 'LAT_MIN', 'LAT_MAX', 'T_REC_dt', 'year', 'NOAA_AR']

Grouped cadence check within HARPNUM:
T_REC_dt
0 days 01:00:00    77115
0 days 02:00:00     8002
0 days 03:00:00     1063
0 days 05:00:00      514
0 days 06:00:00      152
0 days 04:00:00      135
0 days 08:00:00       97
0 days 07:00:00       37
0 days 09:00:00       33
0 days 11:00:00       23
0 days 10:00:00       17
0 days 12:00:00       13
0 days 17:00:00       13
0 days 14:00:00       12
0 days 13:00:00       12
0 days 15:00:00        7
0 days 22:00:00        6
0 days 16:00:00        6
0 days 20:00:00        5
1 days 02:00:00        5
Name: count, dtype: int64

In [ ]:
all_years = list(range(2010, 2026))
year_shapes = {}

for yr in tqdm(all_years, desc="Extracting hourly SHARP by year"):
    try:
        df_year = fetch_hourly_sharp_year(yr, chunk_days=7)
        year_shapes[yr] = None if df_year is None else df_year.shape
    except Exception as e:
        print(f"Year {yr} failed: {e}")
        year_shapes[yr] = "FAILED"

print("\nDONE.")
print(year_shapes)

Extracting hourly SHARP by year:   0%|          | 0/16 [00:00<?, ?it/s]

======================================================================
FETCHING YEAR 2010
======================================================================
Trying query: hmi.sharp_cea_720s[][2010.01.01_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.01.01_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.01.01_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.01.01_00:00_TAI/7d]
Chunk failed for 2010-01-01 00:00:00: All query variants failed for chunk starting 2010-01-01 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.01.08_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.01.08_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.01.08_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.01.08_00:00_TAI/7d]
Chunk failed for 2010-01-08 00:00:00: All query variants failed for chunk starting 2010-01-08 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.01.15_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.01.15_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.01.15_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.01.15_00:00_TAI/7d]
Chunk failed for 2010-01-15 00:00:00: All query variants failed for chunk starting 2010-01-15 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.01.22_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.01.22_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.01.22_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.01.22_00:00_TAI/7d]
Chunk failed for 2010-01-22 00:00:00: All query variants failed for chunk starting 2010-01-22 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.01.29_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.01.29_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.01.29_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.01.29_00:00_TAI/7d]
Chunk failed for 2010-01-29 00:00:00: All query variants failed for chunk starting 2010-01-29 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.02.05_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.02.05_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.02.05_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.02.05_00:00_TAI/7d]
Chunk failed for 2010-02-05 00:00:00: All query variants failed for chunk starting 2010-02-05 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.02.12_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.02.12_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.02.12_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.02.12_00:00_TAI/7d]
Chunk failed for 2010-02-12 00:00:00: All query variants failed for chunk starting 2010-02-12 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.02.19_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.02.19_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.02.19_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.02.19_00:00_TAI/7d]
Chunk failed for 2010-02-19 00:00:00: All query variants failed for chunk starting 2010-02-19 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.02.26_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.02.26_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.02.26_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.02.26_00:00_TAI/7d]
Chunk failed for 2010-02-26 00:00:00: All query variants failed for chunk starting 2010-02-26 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.03.05_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.03.05_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.03.05_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.03.05_00:00_TAI/7d]
Chunk failed for 2010-03-05 00:00:00: All query variants failed for chunk starting 2010-03-05 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.03.12_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.03.12_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.03.12_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.03.12_00:00_TAI/7d]
Chunk failed for 2010-03-12 00:00:00: All query variants failed for chunk starting 2010-03-12 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.03.19_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.03.19_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.03.19_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.03.19_00:00_TAI/7d]
Chunk failed for 2010-03-19 00:00:00: All query variants failed for chunk starting 2010-03-19 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.03.26_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.03.26_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.03.26_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.03.26_00:00_TAI/7d]
Chunk failed for 2010-03-26 00:00:00: All query variants failed for chunk starting 2010-03-26 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.04.02_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.04.02_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.04.02_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.04.02_00:00_TAI/7d]
Chunk failed for 2010-04-02 00:00:00: All query variants failed for chunk starting 2010-04-02 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.04.09_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.04.09_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.04.09_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.04.09_00:00_TAI/7d]
Chunk failed for 2010-04-09 00:00:00: All query variants failed for chunk starting 2010-04-09 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.04.16_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.04.16_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.04.16_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.04.16_00:00_TAI/7d]
Chunk failed for 2010-04-16 00:00:00: All query variants failed for chunk starting 2010-04-16 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.04.23_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.04.23_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2010.04.23_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2010.04.23_00:00_TAI/7d]
Chunk failed for 2010-04-23 00:00:00: All query variants failed for chunk starting 2010-04-23 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2010.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-04-30 00:00:00 -> rows=701

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-05-07 00:00:00 -> rows=384

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-05-14 00:00:00 -> rows=178

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-05-21 00:00:00 -> rows=738

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-05-28 00:00:00 -> rows=733

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-06-04 00:00:00 -> rows=510

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-06-11 00:00:00 -> rows=405

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-06-18 00:00:00 -> rows=360

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-06-25 00:00:00 -> rows=750

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-07-02 00:00:00 -> rows=641

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-07-09 00:00:00 -> rows=297

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-07-16 00:00:00 -> rows=372

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-07-23 00:00:00 -> rows=641

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-07-30 00:00:00 -> rows=714

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-08-06 00:00:00 -> rows=937

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-08-13 00:00:00 -> rows=754

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-08-20 00:00:00 -> rows=385

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-08-27 00:00:00 -> rows=639

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-09-03 00:00:00 -> rows=736

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-09-10 00:00:00 -> rows=895

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-09-17 00:00:00 -> rows=534

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-09-24 00:00:00 -> rows=569

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-10-01 00:00:00 -> rows=446

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-10-08 00:00:00 -> rows=336

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-10-15 00:00:00 -> rows=951

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-10-22 00:00:00 -> rows=926

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-10-29 00:00:00 -> rows=353

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-11-05 00:00:00 -> rows=508

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-11-12 00:00:00 -> rows=794

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-11-19 00:00:00 -> rows=561

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-11-26 00:00:00 -> rows=452

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-12-03 00:00:00 -> rows=1042

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-12-10 00:00:00 -> rows=757

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-12-17 00:00:00 -> rows=723

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2010.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2010-12-24 00:00:00 -> rows=596

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2010.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2010.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2010-12-31 00:00:00 -> rows=134

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2010 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2010.csv
Final shape: (21452, 29)

======================================================================
FETCHING YEAR 2011
======================================================================
Trying query: hmi.sharp_cea_720s[][2011.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-01-01 00:00:00 -> rows=994

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-01-08 00:00:00 -> rows=723

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-01-15 00:00:00 -> rows=370

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-01-22 00:00:00 -> rows=201

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-01-29 00:00:00 -> rows=583

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-02-05 00:00:00 -> rows=774

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-02-12 00:00:00 -> rows=1303

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-02-19 00:00:00 -> rows=524

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-02-26 00:00:00 -> rows=661

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-03-05 00:00:00 -> rows=1214

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-03-12 00:00:00 -> rows=893

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-03-19 00:00:00 -> rows=639

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-03-26 00:00:00 -> rows=1084

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-04-02 00:00:00 -> rows=1158

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-04-09 00:00:00 -> rows=962

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-04-16 00:00:00 -> rows=723

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.04.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.04.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-04-23 00:00:00 -> rows=1454

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-04-30 00:00:00 -> rows=1557

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-05-07 00:00:00 -> rows=1146

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-05-14 00:00:00 -> rows=1253

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-05-21 00:00:00 -> rows=1405

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-05-28 00:00:00 -> rows=1295

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-06-04 00:00:00 -> rows=897

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-06-11 00:00:00 -> rows=934

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-06-18 00:00:00 -> rows=980

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-06-25 00:00:00 -> rows=1010

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-07-02 00:00:00 -> rows=925

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-07-09 00:00:00 -> rows=1177

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-07-16 00:00:00 -> rows=1220

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-07-23 00:00:00 -> rows=1054

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-07-30 00:00:00 -> rows=1078

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-08-06 00:00:00 -> rows=1425

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-08-13 00:00:00 -> rows=1602

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-08-20 00:00:00 -> rows=1095

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-08-27 00:00:00 -> rows=1239

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-09-03 00:00:00 -> rows=1129

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-09-10 00:00:00 -> rows=1365

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-09-17 00:00:00 -> rows=1319

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-09-24 00:00:00 -> rows=1210

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-10-01 00:00:00 -> rows=1675

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-10-08 00:00:00 -> rows=1692

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-10-15 00:00:00 -> rows=1580

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-10-22 00:00:00 -> rows=1253

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-10-29 00:00:00 -> rows=1606

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-11-05 00:00:00 -> rows=1400

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-11-12 00:00:00 -> rows=2399

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-11-19 00:00:00 -> rows=1429

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-11-26 00:00:00 -> rows=1015

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-12-03 00:00:00 -> rows=1592

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-12-10 00:00:00 -> rows=1781

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-12-17 00:00:00 -> rows=2088

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2011.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2011-12-24 00:00:00 -> rows=1841

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2011.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2011.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2011-12-31 00:00:00 -> rows=219

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2011 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2011.csv
Final shape: (62145, 29)

======================================================================
FETCHING YEAR 2012
======================================================================
Trying query: hmi.sharp_cea_720s[][2012.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-01-01 00:00:00 -> rows=1660

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-01-08 00:00:00 -> rows=1487

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-01-15 00:00:00 -> rows=1693

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-01-22 00:00:00 -> rows=1245

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-01-29 00:00:00 -> rows=1617

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-02-05 00:00:00 -> rows=998

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-02-12 00:00:00 -> rows=1171

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-02-19 00:00:00 -> rows=922

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-02-26 00:00:00 -> rows=1289

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.03.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.03.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-03-04 00:00:00 -> rows=1122

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.03.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.03.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-03-11 00:00:00 -> rows=1119

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.03.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.03.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-03-18 00:00:00 -> rows=1219

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.03.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.03.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-03-25 00:00:00 -> rows=1117

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.04.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.04.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-04-01 00:00:00 -> rows=1059

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.04.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.04.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-04-08 00:00:00 -> rows=1507

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.04.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.04.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-04-15 00:00:00 -> rows=1561

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.04.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.04.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-04-22 00:00:00 -> rows=1521

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.04.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.04.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-04-29 00:00:00 -> rows=1177

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.05.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.05.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-05-06 00:00:00 -> rows=1375

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.05.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.05.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-05-13 00:00:00 -> rows=1854

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.05.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.05.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-05-20 00:00:00 -> rows=2104

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.05.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.05.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-05-27 00:00:00 -> rows=1620

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.06.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.06.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-06-03 00:00:00 -> rows=1220

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.06.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.06.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-06-10 00:00:00 -> rows=1203

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.06.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.06.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-06-17 00:00:00 -> rows=1284

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.06.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.06.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-06-24 00:00:00 -> rows=1410

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.07.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.07.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-07-01 00:00:00 -> rows=1025

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.07.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.07.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-07-08 00:00:00 -> rows=750

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.07.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.07.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-07-15 00:00:00 -> rows=658

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.07.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.07.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-07-22 00:00:00 -> rows=833

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.07.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.07.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-07-29 00:00:00 -> rows=1265

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.08.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.08.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-08-05 00:00:00 -> rows=1314

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.08.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.08.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-08-12 00:00:00 -> rows=654

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.08.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.08.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-08-19 00:00:00 -> rows=1551

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.08.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.08.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-08-26 00:00:00 -> rows=2551

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.09.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.09.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-09-02 00:00:00 -> rows=1751

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.09.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.09.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-09-09 00:00:00 -> rows=872

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.09.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.09.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-09-16 00:00:00 -> rows=1099

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.09.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.09.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-09-23 00:00:00 -> rows=1620

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.09.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.09.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-09-30 00:00:00 -> rows=1544

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.10.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.10.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-10-07 00:00:00 -> rows=573

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.10.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.10.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-10-14 00:00:00 -> rows=1184

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.10.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.10.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-10-21 00:00:00 -> rows=1707

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.10.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.10.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-10-28 00:00:00 -> rows=1545

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.11.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.11.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-11-04 00:00:00 -> rows=1283

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.11.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.11.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-11-11 00:00:00 -> rows=1075

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.11.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.11.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-11-18 00:00:00 -> rows=1360

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.11.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.11.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-11-25 00:00:00 -> rows=1138

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.12.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.12.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-12-02 00:00:00 -> rows=1166

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.12.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.12.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-12-09 00:00:00 -> rows=2044

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.12.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.12.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-12-16 00:00:00 -> rows=1131

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.12.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2012.12.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2012-12-23 00:00:00 -> rows=875

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2012.12.30_00:00:00_TAI/2d@1h]
Success with: hmi.sharp_cea_720s[][2012.12.30_00:00:00_TAI/2d@1h]
Chunk saved in memory: 2012-12-30 00:00:00 -> rows=364

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2012 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2012.csv
Final shape: (68486, 29)

======================================================================
FETCHING YEAR 2013
======================================================================
Trying query: hmi.sharp_cea_720s[][2013.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-01-01 00:00:00 -> rows=2180

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-01-08 00:00:00 -> rows=1827

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-01-15 00:00:00 -> rows=1351

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-01-22 00:00:00 -> rows=1207

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-01-29 00:00:00 -> rows=1957

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-02-05 00:00:00 -> rows=2376

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-02-12 00:00:00 -> rows=1875

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-02-19 00:00:00 -> rows=897

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-02-26 00:00:00 -> rows=1130

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-03-05 00:00:00 -> rows=1797

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-03-12 00:00:00 -> rows=1771

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-03-19 00:00:00 -> rows=1369

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-03-26 00:00:00 -> rows=1504

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-04-02 00:00:00 -> rows=1905

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-04-09 00:00:00 -> rows=1708

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-04-16 00:00:00 -> rows=1061

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.04.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.04.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-04-23 00:00:00 -> rows=223

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-04-30 00:00:00 -> rows=1375

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-05-07 00:00:00 -> rows=1535

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-05-14 00:00:00 -> rows=1620

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-05-21 00:00:00 -> rows=1120

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-05-28 00:00:00 -> rows=1737

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-06-04 00:00:00 -> rows=1548

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-06-11 00:00:00 -> rows=1336

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-06-18 00:00:00 -> rows=1309

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-06-25 00:00:00 -> rows=1629

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-07-02 00:00:00 -> rows=1462

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-07-09 00:00:00 -> rows=1422

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-07-16 00:00:00 -> rows=1806

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-07-23 00:00:00 -> rows=1692

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-07-30 00:00:00 -> rows=2059

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-08-06 00:00:00 -> rows=1870

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-08-13 00:00:00 -> rows=2100

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-08-20 00:00:00 -> rows=1807

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-08-27 00:00:00 -> rows=1470

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-09-03 00:00:00 -> rows=982

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-09-10 00:00:00 -> rows=1612

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-09-17 00:00:00 -> rows=1142

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-09-24 00:00:00 -> rows=1487

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-10-01 00:00:00 -> rows=1463

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-10-08 00:00:00 -> rows=1439

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-10-15 00:00:00 -> rows=1427

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-10-22 00:00:00 -> rows=1560

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-10-29 00:00:00 -> rows=1826

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-11-05 00:00:00 -> rows=2109

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-11-12 00:00:00 -> rows=1714

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-11-19 00:00:00 -> rows=1872

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-11-26 00:00:00 -> rows=1657

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-12-03 00:00:00 -> rows=1883

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-12-10 00:00:00 -> rows=1593

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-12-17 00:00:00 -> rows=1334

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2013.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2013-12-24 00:00:00 -> rows=1503

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2013.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2013.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2013-12-31 00:00:00 -> rows=237

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2013 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2013.csv
Final shape: (81875, 29)

======================================================================
FETCHING YEAR 2014
======================================================================
Trying query: hmi.sharp_cea_720s[][2014.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-01-01 00:00:00 -> rows=1840

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-01-08 00:00:00 -> rows=2455

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-01-15 00:00:00 -> rows=1454

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-01-22 00:00:00 -> rows=1233

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-01-29 00:00:00 -> rows=1014

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-02-05 00:00:00 -> rows=1986

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-02-12 00:00:00 -> rows=1472

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-02-19 00:00:00 -> rows=1574

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-02-26 00:00:00 -> rows=1270

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-03-05 00:00:00 -> rows=1523

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-03-12 00:00:00 -> rows=1314

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-03-19 00:00:00 -> rows=1844

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-03-26 00:00:00 -> rows=2216

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-04-02 00:00:00 -> rows=1836

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-04-09 00:00:00 -> rows=1674

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-04-16 00:00:00 -> rows=2306

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.04.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.04.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-04-23 00:00:00 -> rows=2543

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-04-30 00:00:00 -> rows=1898

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-05-07 00:00:00 -> rows=1831

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-05-14 00:00:00 -> rows=1797

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-05-21 00:00:00 -> rows=1210

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-05-28 00:00:00 -> rows=1321

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-06-04 00:00:00 -> rows=1347

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-06-11 00:00:00 -> rows=1984

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-06-18 00:00:00 -> rows=1328

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-06-25 00:00:00 -> rows=1250

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-07-02 00:00:00 -> rows=1774

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-07-09 00:00:00 -> rows=1591

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-07-16 00:00:00 -> rows=1092

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-07-23 00:00:00 -> rows=1295

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-07-30 00:00:00 -> rows=1797

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-08-06 00:00:00 -> rows=1402

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-08-13 00:00:00 -> rows=1386

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-08-20 00:00:00 -> rows=1042

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-08-27 00:00:00 -> rows=1640

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-09-03 00:00:00 -> rows=1935

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-09-10 00:00:00 -> rows=1710

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-09-17 00:00:00 -> rows=1631

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-09-24 00:00:00 -> rows=1870

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-10-01 00:00:00 -> rows=1665

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-10-08 00:00:00 -> rows=1358

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-10-15 00:00:00 -> rows=1929

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-10-22 00:00:00 -> rows=1612

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-10-29 00:00:00 -> rows=2356

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-11-05 00:00:00 -> rows=1942

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-11-12 00:00:00 -> rows=1729

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-11-19 00:00:00 -> rows=1429

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-11-26 00:00:00 -> rows=1937

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-12-03 00:00:00 -> rows=1910

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-12-10 00:00:00 -> rows=1758

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-12-17 00:00:00 -> rows=1843

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2014.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2014-12-24 00:00:00 -> rows=2622

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2014.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2014.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2014-12-31 00:00:00 -> rows=288

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2014 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2014.csv
Final shape: (88063, 29)

======================================================================
FETCHING YEAR 2015
======================================================================
Trying query: hmi.sharp_cea_720s[][2015.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-01-01 00:00:00 -> rows=1579

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-01-08 00:00:00 -> rows=1655

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-01-15 00:00:00 -> rows=2124

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-01-22 00:00:00 -> rows=1678

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-01-29 00:00:00 -> rows=2302

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-02-05 00:00:00 -> rows=2382

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-02-12 00:00:00 -> rows=1879

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-02-19 00:00:00 -> rows=1558

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-02-26 00:00:00 -> rows=1157

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-03-05 00:00:00 -> rows=1930

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-03-12 00:00:00 -> rows=1922

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-03-19 00:00:00 -> rows=1899

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-03-26 00:00:00 -> rows=1509

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-04-02 00:00:00 -> rows=2054

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-04-09 00:00:00 -> rows=1287

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-04-16 00:00:00 -> rows=1768

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.04.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.04.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-04-23 00:00:00 -> rows=1915

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-04-30 00:00:00 -> rows=1594

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-05-07 00:00:00 -> rows=1588

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-05-14 00:00:00 -> rows=2294

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-05-21 00:00:00 -> rows=1655

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-05-28 00:00:00 -> rows=997

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-06-04 00:00:00 -> rows=1329

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-06-11 00:00:00 -> rows=1894

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-06-18 00:00:00 -> rows=1269

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-06-25 00:00:00 -> rows=834

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-07-02 00:00:00 -> rows=1704

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-07-09 00:00:00 -> rows=1984

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-07-16 00:00:00 -> rows=893

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-07-23 00:00:00 -> rows=1100

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-07-30 00:00:00 -> rows=1834

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-08-06 00:00:00 -> rows=1780

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-08-13 00:00:00 -> rows=927

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-08-20 00:00:00 -> rows=886

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-08-27 00:00:00 -> rows=1385

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-09-03 00:00:00 -> rows=1055

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-09-10 00:00:00 -> rows=832

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-09-17 00:00:00 -> rows=1062

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-09-24 00:00:00 -> rows=1519

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-10-01 00:00:00 -> rows=686

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-10-08 00:00:00 -> rows=933

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-10-15 00:00:00 -> rows=1670

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-10-22 00:00:00 -> rows=979

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-10-29 00:00:00 -> rows=1195

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-11-05 00:00:00 -> rows=831

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-11-12 00:00:00 -> rows=1431

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-11-19 00:00:00 -> rows=1233

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-11-26 00:00:00 -> rows=682

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-12-03 00:00:00 -> rows=1245

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-12-10 00:00:00 -> rows=1834

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-12-17 00:00:00 -> rows=1371

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2015.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2015-12-24 00:00:00 -> rows=788

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2015.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2015.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2015-12-31 00:00:00 -> rows=90

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2015 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2015.csv
Final shape: (75981, 29)

======================================================================
FETCHING YEAR 2016
======================================================================
Trying query: hmi.sharp_cea_720s[][2016.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-01-01 00:00:00 -> rows=1239

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-01-08 00:00:00 -> rows=1456

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-01-15 00:00:00 -> rows=1279

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-01-22 00:00:00 -> rows=771

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-01-29 00:00:00 -> rows=1190

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-02-05 00:00:00 -> rows=1697

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-02-12 00:00:00 -> rows=1378

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-02-19 00:00:00 -> rows=1089

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-02-26 00:00:00 -> rows=859

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.03.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.03.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-03-04 00:00:00 -> rows=942

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.03.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.03.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-03-11 00:00:00 -> rows=1005

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.03.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.03.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-03-18 00:00:00 -> rows=778

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.03.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.03.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-03-25 00:00:00 -> rows=686

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.04.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.04.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-04-01 00:00:00 -> rows=1056

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.04.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.04.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-04-08 00:00:00 -> rows=736

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.04.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.04.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-04-15 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.04.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.04.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-04-22 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.04.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.04.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-04-29 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.05.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.05.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-05-06 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.05.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.05.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-05-13 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.05.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.05.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-05-20 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.05.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.05.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-05-27 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.06.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.06.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-06-03 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.06.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.06.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-06-10 00:00:00 -> rows=184

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.06.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.06.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-06-17 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.06.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.06.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-06-24 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.07.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.07.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-07-01 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.07.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.07.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-07-08 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.07.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.07.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-07-15 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.07.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.07.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-07-22 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.07.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.07.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-07-29 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.08.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.08.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-08-05 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.08.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.08.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-08-12 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.08.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.08.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-08-19 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.08.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.08.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-08-26 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.09.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.09.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-09-02 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.09.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.09.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-09-09 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.09.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.09.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-09-16 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.09.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.09.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-09-23 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.09.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.09.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-09-30 00:00:00 -> rows=43

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.10.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.10.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-10-07 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.10.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.10.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-10-14 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.10.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.10.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-10-21 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.10.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.10.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-10-28 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.11.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.11.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-11-04 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.11.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.11.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-11-11 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.11.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.11.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-11-18 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.11.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.11.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-11-25 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.12.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.12.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-12-02 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.12.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.12.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-12-09 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.12.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.12.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-12-16 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.12.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2016.12.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2016-12-23 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2016.12.30_00:00:00_TAI/2d@1h]
Success with: hmi.sharp_cea_720s[][2016.12.30_00:00:00_TAI/2d@1h]
Chunk saved in memory: 2016-12-30 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2016 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2016.csv
Final shape: (16388, 29)

======================================================================
FETCHING YEAR 2017
======================================================================
Trying query: hmi.sharp_cea_720s[][2017.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-01-01 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-01-08 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-01-15 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-01-22 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-01-29 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-02-05 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-02-12 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-02-19 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-02-26 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-03-05 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-03-12 00:00:00 -> rows=63

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-03-19 00:00:00 -> rows=300

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-03-26 00:00:00 -> rows=694

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-04-02 00:00:00 -> rows=495

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-04-09 00:00:00 -> rows=220

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-04-16 00:00:00 -> rows=360

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.04.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.04.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-04-23 00:00:00 -> rows=443

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-04-30 00:00:00 -> rows=309

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-05-07 00:00:00 -> rows=180

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-05-14 00:00:00 -> rows=419

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-05-21 00:00:00 -> rows=894

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-05-28 00:00:00 -> rows=369

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-06-04 00:00:00 -> rows=495

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-06-11 00:00:00 -> rows=528

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-06-18 00:00:00 -> rows=662

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-06-25 00:00:00 -> rows=248

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-07-02 00:00:00 -> rows=403

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-07-09 00:00:00 -> rows=515

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-07-16 00:00:00 -> rows=368

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-07-23 00:00:00 -> rows=363

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-07-30 00:00:00 -> rows=65

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-08-06 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-08-13 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-08-20 00:00:00 -> rows=0

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-08-27 00:00:00 -> rows=555

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-09-03 00:00:00 -> rows=775

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-09-10 00:00:00 -> rows=501

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-09-17 00:00:00 -> rows=673

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-09-24 00:00:00 -> rows=582

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-10-01 00:00:00 -> rows=349

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-10-08 00:00:00 -> rows=160

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-10-15 00:00:00 -> rows=375

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-10-22 00:00:00 -> rows=686

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-10-29 00:00:00 -> rows=280

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-11-05 00:00:00 -> rows=193

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-11-12 00:00:00 -> rows=211

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-11-19 00:00:00 -> rows=571

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-11-26 00:00:00 -> rows=219

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-12-03 00:00:00 -> rows=88

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-12-10 00:00:00 -> rows=323

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-12-17 00:00:00 -> rows=403

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2017.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2017-12-24 00:00:00 -> rows=177

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2017.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2017.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2017-12-31 00:00:00 -> rows=44

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2017 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2017.csv
Final shape: (15558, 29)

======================================================================
FETCHING YEAR 2018
======================================================================
Trying query: hmi.sharp_cea_720s[][2018.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-01-01 00:00:00 -> rows=267

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-01-08 00:00:00 -> rows=164

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-01-15 00:00:00 -> rows=200

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-01-22 00:00:00 -> rows=18

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-01-29 00:00:00 -> rows=160

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-02-05 00:00:00 -> rows=245

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-02-12 00:00:00 -> rows=97

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.02.19_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2018.02.19_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2018.02.19_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2018.02.19_00:00_TAI/7d]
Chunk failed for 2018-02-19 00:00:00: All query variants failed for chunk starting 2018-02-19 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2018.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-02-26 00:00:00 -> rows=81

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-03-05 00:00:00 -> rows=264

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-03-12 00:00:00 -> rows=119

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-03-19 00:00:00 -> rows=5

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-03-26 00:00:00 -> rows=74

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-04-02 00:00:00 -> rows=113

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-04-09 00:00:00 -> rows=114

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-04-16 00:00:00 -> rows=226

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.04.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.04.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-04-23 00:00:00 -> rows=143

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-04-30 00:00:00 -> rows=68

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-05-07 00:00:00 -> rows=411

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-05-14 00:00:00 -> rows=107

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-05-21 00:00:00 -> rows=455

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-05-28 00:00:00 -> rows=207

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-06-04 00:00:00 -> rows=153

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-06-11 00:00:00 -> rows=144

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-06-18 00:00:00 -> rows=522

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-06-25 00:00:00 -> rows=320

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.07.02_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2018.07.02_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2018.07.02_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2018.07.02_00:00_TAI/7d]
Chunk failed for 2018-07-02 00:00:00: All query variants failed for chunk starting 2018-07-02 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2018.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-07-09 00:00:00 -> rows=142

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-07-16 00:00:00 -> rows=211

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-07-23 00:00:00 -> rows=52

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-07-30 00:00:00 -> rows=103

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-08-06 00:00:00 -> rows=369

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-08-13 00:00:00 -> rows=130

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-08-20 00:00:00 -> rows=156

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-08-27 00:00:00 -> rows=72

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-09-03 00:00:00 -> rows=311

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-09-10 00:00:00 -> rows=179

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-09-17 00:00:00 -> rows=126

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-09-24 00:00:00 -> rows=31

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-10-01 00:00:00 -> rows=60

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-10-08 00:00:00 -> rows=77

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-10-15 00:00:00 -> rows=327

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-10-22 00:00:00 -> rows=5

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.10.29_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2018.10.29_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2018.10.29_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2018.10.29_00:00_TAI/7d]
Chunk failed for 2018-10-29 00:00:00: All query variants failed for chunk starting 2018-10-29 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2018.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-11-05 00:00:00 -> rows=38

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-11-12 00:00:00 -> rows=151

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-11-19 00:00:00 -> rows=69

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-11-26 00:00:00 -> rows=48

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-12-03 00:00:00 -> rows=100

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-12-10 00:00:00 -> rows=160

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-12-17 00:00:00 -> rows=99

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2018.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2018-12-24 00:00:00 -> rows=140

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2018.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2018.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2018-12-31 00:00:00 -> rows=33

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2018 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2018.csv
Final shape: (7866, 29)

======================================================================
FETCHING YEAR 2019
======================================================================
Trying query: hmi.sharp_cea_720s[][2019.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-01-01 00:00:00 -> rows=121

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.01.08_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.01.08_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.01.08_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2019.01.08_00:00_TAI/7d]
Chunk failed for 2019-01-08 00:00:00: All query variants failed for chunk starting 2019-01-08 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2019.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-01-15 00:00:00 -> rows=15

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-01-22 00:00:00 -> rows=311

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-01-29 00:00:00 -> rows=116

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-02-05 00:00:00 -> rows=135

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-02-12 00:00:00 -> rows=98

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-02-19 00:00:00 -> rows=121

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-02-26 00:00:00 -> rows=34

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-03-05 00:00:00 -> rows=265

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-03-12 00:00:00 -> rows=134

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-03-19 00:00:00 -> rows=264

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-03-26 00:00:00 -> rows=30

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-04-02 00:00:00 -> rows=190

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-04-09 00:00:00 -> rows=146

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-04-16 00:00:00 -> rows=159

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.04.23_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.04.23_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.04.23_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2019.04.23_00:00_TAI/7d]
Chunk failed for 2019-04-23 00:00:00: All query variants failed for chunk starting 2019-04-23 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2019.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-04-30 00:00:00 -> rows=90

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-05-07 00:00:00 -> rows=455

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-05-14 00:00:00 -> rows=188

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-05-21 00:00:00 -> rows=14

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-05-28 00:00:00 -> rows=86

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-06-04 00:00:00 -> rows=429

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-06-11 00:00:00 -> rows=55

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-06-18 00:00:00 -> rows=17

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-06-25 00:00:00 -> rows=173

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-07-02 00:00:00 -> rows=167

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-07-09 00:00:00 -> rows=98

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-07-16 00:00:00 -> rows=27

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-07-23 00:00:00 -> rows=25

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-07-30 00:00:00 -> rows=16

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-08-06 00:00:00 -> rows=72

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.08.13_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.08.13_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.08.13_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2019.08.13_00:00_TAI/7d]
Chunk failed for 2019-08-13 00:00:00: All query variants failed for chunk starting 2019-08-13 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2019.08.20_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.08.20_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.08.20_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2019.08.20_00:00_TAI/7d]
Chunk failed for 2019-08-20 00:00:00: All query variants failed for chunk starting 2019-08-20 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2019.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-08-27 00:00:00 -> rows=38

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-09-03 00:00:00 -> rows=56

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.09.10_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.09.10_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.09.10_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2019.09.10_00:00_TAI/7d]
Chunk failed for 2019-09-10 00:00:00: All query variants failed for chunk starting 2019-09-10 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2019.09.17_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.09.17_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.09.17_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2019.09.17_00:00_TAI/7d]
Chunk failed for 2019-09-17 00:00:00: All query variants failed for chunk starting 2019-09-17 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2019.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-09-24 00:00:00 -> rows=4

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-10-01 00:00:00 -> rows=148

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-10-08 00:00:00 -> rows=24

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.10.15_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.10.15_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.10.15_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2019.10.15_00:00_TAI/7d]
Chunk failed for 2019-10-15 00:00:00: All query variants failed for chunk starting 2019-10-15 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2019.10.22_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.10.22_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.10.22_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2019.10.22_00:00_TAI/7d]
Chunk failed for 2019-10-22 00:00:00: All query variants failed for chunk starting 2019-10-22 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2019.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-10-29 00:00:00 -> rows=121

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-11-05 00:00:00 -> rows=65

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-11-12 00:00:00 -> rows=145

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-11-19 00:00:00 -> rows=29

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.11.26_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.11.26_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.11.26_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2019.11.26_00:00_TAI/7d]
Chunk failed for 2019-11-26 00:00:00: All query variants failed for chunk starting 2019-11-26 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2019.12.03_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.12.03_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.12.03_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2019.12.03_00:00_TAI/7d]
Chunk failed for 2019-12-03 00:00:00: All query variants failed for chunk starting 2019-12-03 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2019.12.10_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.12.10_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2019.12.10_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2019.12.10_00:00_TAI/7d]
Chunk failed for 2019-12-10 00:00:00: All query variants failed for chunk starting 2019-12-10 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2019.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-12-17 00:00:00 -> rows=33

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2019.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2019-12-24 00:00:00 -> rows=194

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2019.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2019.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2019-12-31 00:00:00 -> rows=9

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2019 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2019.csv
Final shape: (4917, 29)

======================================================================
FETCHING YEAR 2020
======================================================================
Trying query: hmi.sharp_cea_720s[][2020.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-01-01 00:00:00 -> rows=148

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-01-08 00:00:00 -> rows=254

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.01.15_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.01.15_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.01.15_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2020.01.15_00:00_TAI/7d]
Chunk failed for 2020-01-15 00:00:00: All query variants failed for chunk starting 2020-01-15 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2020.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-01-22 00:00:00 -> rows=143

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-01-29 00:00:00 -> rows=192

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-02-05 00:00:00 -> rows=13

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.02.12_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.02.12_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.02.12_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2020.02.12_00:00_TAI/7d]
Chunk failed for 2020-02-12 00:00:00: All query variants failed for chunk starting 2020-02-12 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2020.02.19_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.02.19_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.02.19_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2020.02.19_00:00_TAI/7d]
Chunk failed for 2020-02-19 00:00:00: All query variants failed for chunk starting 2020-02-19 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2020.02.26_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.02.26_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.02.26_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2020.02.26_00:00_TAI/7d]
Chunk failed for 2020-02-26 00:00:00: All query variants failed for chunk starting 2020-02-26 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2020.03.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.03.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-03-04 00:00:00 -> rows=74

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.03.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.03.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-03-11 00:00:00 -> rows=86

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.03.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.03.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-03-18 00:00:00 -> rows=4

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.03.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.03.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-03-25 00:00:00 -> rows=46

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.04.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.04.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-04-01 00:00:00 -> rows=149

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.04.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.04.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-04-08 00:00:00 -> rows=17

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.04.15_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.04.15_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.04.15_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2020.04.15_00:00_TAI/7d]
Chunk failed for 2020-04-15 00:00:00: All query variants failed for chunk starting 2020-04-15 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2020.04.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.04.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-04-22 00:00:00 -> rows=121

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.04.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.04.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-04-29 00:00:00 -> rows=211

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.05.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.05.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-05-06 00:00:00 -> rows=1

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.05.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.05.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-05-13 00:00:00 -> rows=27

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.05.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.05.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-05-20 00:00:00 -> rows=150

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.05.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.05.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-05-27 00:00:00 -> rows=176

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.06.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.06.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-06-03 00:00:00 -> rows=366

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.06.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.06.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-06-10 00:00:00 -> rows=130

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.06.17_00:00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.06.17_00:00_TAI/7d@1h]
Trying query: hmi.sharp_cea_720s[][2020.06.17_00:00:00_TAI/7d]
Trying query: hmi.sharp_cea_720s[][2020.06.17_00:00_TAI/7d]
Chunk failed for 2020-06-17 00:00:00: All query variants failed for chunk starting 2020-06-17 00:00:00. Last error: None
Trying query: hmi.sharp_cea_720s[][2020.06.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.06.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-06-24 00:00:00 -> rows=51

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.07.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.07.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-07-01 00:00:00 -> rows=170

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.07.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.07.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-07-08 00:00:00 -> rows=11

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.07.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.07.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-07-15 00:00:00 -> rows=98

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.07.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.07.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-07-22 00:00:00 -> rows=181

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.07.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.07.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-07-29 00:00:00 -> rows=354

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.08.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.08.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-08-05 00:00:00 -> rows=349

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.08.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.08.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-08-12 00:00:00 -> rows=254

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.08.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.08.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-08-19 00:00:00 -> rows=129

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.08.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.08.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-08-26 00:00:00 -> rows=132

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.09.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.09.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-09-02 00:00:00 -> rows=72

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.09.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.09.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-09-09 00:00:00 -> rows=53

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.09.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.09.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-09-16 00:00:00 -> rows=25

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.09.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.09.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-09-23 00:00:00 -> rows=242

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.09.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.09.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-09-30 00:00:00 -> rows=101

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.10.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.10.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-10-07 00:00:00 -> rows=218

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.10.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.10.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-10-14 00:00:00 -> rows=229

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.10.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.10.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-10-21 00:00:00 -> rows=427

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.10.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.10.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-10-28 00:00:00 -> rows=207

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.11.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.11.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-11-04 00:00:00 -> rows=377

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.11.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.11.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-11-11 00:00:00 -> rows=370

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.11.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.11.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-11-18 00:00:00 -> rows=387

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.11.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.11.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-11-25 00:00:00 -> rows=623

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.12.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.12.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-12-02 00:00:00 -> rows=732

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.12.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.12.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-12-09 00:00:00 -> rows=437

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.12.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.12.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-12-16 00:00:00 -> rows=594

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.12.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2020.12.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2020-12-23 00:00:00 -> rows=622

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2020.12.30_00:00:00_TAI/2d@1h]
Success with: hmi.sharp_cea_720s[][2020.12.30_00:00:00_TAI/2d@1h]
Chunk saved in memory: 2020-12-30 00:00:00 -> rows=130

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2020 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2020.csv
Final shape: (9883, 29)

======================================================================
FETCHING YEAR 2021
======================================================================
Trying query: hmi.sharp_cea_720s[][2021.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-01-01 00:00:00 -> rows=513

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-01-08 00:00:00 -> rows=164

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-01-15 00:00:00 -> rows=317

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-01-22 00:00:00 -> rows=615

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-01-29 00:00:00 -> rows=125

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-02-05 00:00:00 -> rows=66

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-02-12 00:00:00 -> rows=190

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-02-19 00:00:00 -> rows=369

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-02-26 00:00:00 -> rows=320

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-03-05 00:00:00 -> rows=449

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-03-12 00:00:00 -> rows=343

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-03-19 00:00:00 -> rows=371

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-03-26 00:00:00 -> rows=438

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-04-02 00:00:00 -> rows=108

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-04-09 00:00:00 -> rows=215

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-04-16 00:00:00 -> rows=474

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.04.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.04.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-04-23 00:00:00 -> rows=322

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-04-30 00:00:00 -> rows=135

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-05-07 00:00:00 -> rows=379

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-05-14 00:00:00 -> rows=568

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-05-21 00:00:00 -> rows=462

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-05-28 00:00:00 -> rows=450

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-06-04 00:00:00 -> rows=790

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-06-11 00:00:00 -> rows=743

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-06-18 00:00:00 -> rows=449

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-06-25 00:00:00 -> rows=1000

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-07-02 00:00:00 -> rows=935

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-07-09 00:00:00 -> rows=536

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-07-16 00:00:00 -> rows=875

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-07-23 00:00:00 -> rows=794

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-07-30 00:00:00 -> rows=464

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-08-06 00:00:00 -> rows=311

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-08-13 00:00:00 -> rows=384

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-08-20 00:00:00 -> rows=692

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-08-27 00:00:00 -> rows=1015

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-09-03 00:00:00 -> rows=960

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-09-10 00:00:00 -> rows=543

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-09-17 00:00:00 -> rows=610

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-09-24 00:00:00 -> rows=1087

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-10-01 00:00:00 -> rows=710

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-10-08 00:00:00 -> rows=895

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-10-15 00:00:00 -> rows=661

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-10-22 00:00:00 -> rows=913

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-10-29 00:00:00 -> rows=1055

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-11-05 00:00:00 -> rows=762

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-11-12 00:00:00 -> rows=497

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-11-19 00:00:00 -> rows=607

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-11-26 00:00:00 -> rows=908

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-12-03 00:00:00 -> rows=490

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-12-10 00:00:00 -> rows=498

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-12-17 00:00:00 -> rows=1280

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2021.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2021-12-24 00:00:00 -> rows=1593

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2021.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2021.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2021-12-31 00:00:00 -> rows=169

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2021 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2021.csv
Final shape: (30619, 29)

======================================================================
FETCHING YEAR 2022
======================================================================
Trying query: hmi.sharp_cea_720s[][2022.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-01-01 00:00:00 -> rows=515

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-01-08 00:00:00 -> rows=1164

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-01-15 00:00:00 -> rows=1636

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-01-22 00:00:00 -> rows=1121

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-01-29 00:00:00 -> rows=844

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-02-05 00:00:00 -> rows=1419

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-02-12 00:00:00 -> rows=1578

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-02-19 00:00:00 -> rows=1318

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-02-26 00:00:00 -> rows=612

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-03-05 00:00:00 -> rows=1107

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-03-12 00:00:00 -> rows=1131

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-03-19 00:00:00 -> rows=987

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-03-26 00:00:00 -> rows=1653

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-04-02 00:00:00 -> rows=1241

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-04-09 00:00:00 -> rows=1544

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-04-16 00:00:00 -> rows=1078

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.04.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.04.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-04-23 00:00:00 -> rows=1824

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-04-30 00:00:00 -> rows=1821

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-05-07 00:00:00 -> rows=1161

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-05-14 00:00:00 -> rows=1281

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-05-21 00:00:00 -> rows=1938

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-05-28 00:00:00 -> rows=1402

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-06-04 00:00:00 -> rows=1102

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-06-11 00:00:00 -> rows=1112

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-06-18 00:00:00 -> rows=1235

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-06-25 00:00:00 -> rows=1582

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-07-02 00:00:00 -> rows=1813

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-07-09 00:00:00 -> rows=1838

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-07-16 00:00:00 -> rows=1589

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-07-23 00:00:00 -> rows=1352

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-07-30 00:00:00 -> rows=1009

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-08-06 00:00:00 -> rows=1527

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-08-13 00:00:00 -> rows=1581

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-08-20 00:00:00 -> rows=1439

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-08-27 00:00:00 -> rows=1401

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-09-03 00:00:00 -> rows=1332

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-09-10 00:00:00 -> rows=1432

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-09-17 00:00:00 -> rows=868

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-09-24 00:00:00 -> rows=996

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-10-01 00:00:00 -> rows=1305

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-10-08 00:00:00 -> rows=2054

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-10-15 00:00:00 -> rows=1464

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-10-22 00:00:00 -> rows=1320

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-10-29 00:00:00 -> rows=1605

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-11-05 00:00:00 -> rows=1535

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-11-12 00:00:00 -> rows=1419

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-11-19 00:00:00 -> rows=1102

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-11-26 00:00:00 -> rows=1371

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-12-03 00:00:00 -> rows=1378

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-12-10 00:00:00 -> rows=1632

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-12-17 00:00:00 -> rows=1491

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2022.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2022-12-24 00:00:00 -> rows=1451

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2022.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2022.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2022-12-31 00:00:00 -> rows=276

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2022 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2022.csv
Final shape: (70986, 29)

======================================================================
FETCHING YEAR 2023
======================================================================
Trying query: hmi.sharp_cea_720s[][2023.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-01-01 00:00:00 -> rows=1527

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-01-08 00:00:00 -> rows=1610

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-01-15 00:00:00 -> rows=1502

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-01-22 00:00:00 -> rows=1237

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-01-29 00:00:00 -> rows=1807

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-02-05 00:00:00 -> rows=1541

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-02-12 00:00:00 -> rows=2079

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-02-19 00:00:00 -> rows=2177

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-02-26 00:00:00 -> rows=2467

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-03-05 00:00:00 -> rows=2704

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-03-12 00:00:00 -> rows=2346

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-03-19 00:00:00 -> rows=1524

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-03-26 00:00:00 -> rows=1841

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-04-02 00:00:00 -> rows=1705

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-04-09 00:00:00 -> rows=2658

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-04-16 00:00:00 -> rows=2150

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.04.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.04.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-04-23 00:00:00 -> rows=2029

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-04-30 00:00:00 -> rows=1668

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-05-07 00:00:00 -> rows=2309

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-05-14 00:00:00 -> rows=1941

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-05-21 00:00:00 -> rows=1106

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-05-28 00:00:00 -> rows=2016

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-06-04 00:00:00 -> rows=2552

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-06-11 00:00:00 -> rows=2282

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-06-18 00:00:00 -> rows=2187

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-06-25 00:00:00 -> rows=1833

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-07-02 00:00:00 -> rows=1989

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-07-09 00:00:00 -> rows=2000

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-07-16 00:00:00 -> rows=2299

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-07-23 00:00:00 -> rows=1445

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-07-30 00:00:00 -> rows=1331

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-08-06 00:00:00 -> rows=2038

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-08-13 00:00:00 -> rows=2407

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-08-20 00:00:00 -> rows=1744

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-08-27 00:00:00 -> rows=2596

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-09-03 00:00:00 -> rows=1815

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-09-10 00:00:00 -> rows=2260

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-09-17 00:00:00 -> rows=1777

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-09-24 00:00:00 -> rows=2102

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-10-01 00:00:00 -> rows=2157

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-10-08 00:00:00 -> rows=2701

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-10-15 00:00:00 -> rows=2895

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-10-22 00:00:00 -> rows=1577

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-10-29 00:00:00 -> rows=2257

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-11-05 00:00:00 -> rows=1908

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-11-12 00:00:00 -> rows=2102

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-11-19 00:00:00 -> rows=1701

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-11-26 00:00:00 -> rows=1890

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-12-03 00:00:00 -> rows=1532

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-12-10 00:00:00 -> rows=1216

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-12-17 00:00:00 -> rows=2124

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2023.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2023-12-24 00:00:00 -> rows=2291

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2023.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2023.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2023-12-31 00:00:00 -> rows=362

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2023 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2023.csv
Final shape: (103314, 29)

======================================================================
FETCHING YEAR 2024
======================================================================
Trying query: hmi.sharp_cea_720s[][2024.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-01-01 00:00:00 -> rows=1938

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-01-08 00:00:00 -> rows=1883

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-01-15 00:00:00 -> rows=2318

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-01-22 00:00:00 -> rows=1929

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-01-29 00:00:00 -> rows=1871

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-02-05 00:00:00 -> rows=1926

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-02-12 00:00:00 -> rows=2383

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-02-19 00:00:00 -> rows=1628

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-02-26 00:00:00 -> rows=1572

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.03.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.03.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-03-04 00:00:00 -> rows=1609

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.03.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.03.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-03-11 00:00:00 -> rows=2442

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.03.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.03.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-03-18 00:00:00 -> rows=1806

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.03.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.03.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-03-25 00:00:00 -> rows=1962

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.04.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.04.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-04-01 00:00:00 -> rows=1962

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.04.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.04.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-04-08 00:00:00 -> rows=2167

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.04.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.04.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-04-15 00:00:00 -> rows=2022

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.04.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.04.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-04-22 00:00:00 -> rows=2127

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.04.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.04.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-04-29 00:00:00 -> rows=2060

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.05.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.05.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-05-06 00:00:00 -> rows=1448

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.05.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.05.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-05-13 00:00:00 -> rows=1866

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.05.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.05.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-05-20 00:00:00 -> rows=1746

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.05.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.05.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-05-27 00:00:00 -> rows=1531

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.06.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.06.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-06-03 00:00:00 -> rows=2390

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.06.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.06.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-06-10 00:00:00 -> rows=2734

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.06.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.06.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-06-17 00:00:00 -> rows=1583

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.06.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.06.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-06-24 00:00:00 -> rows=1236

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.07.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.07.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-07-01 00:00:00 -> rows=1652

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.07.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.07.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-07-08 00:00:00 -> rows=1974

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.07.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.07.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-07-15 00:00:00 -> rows=1963

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.07.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.07.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-07-22 00:00:00 -> rows=1752

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.07.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.07.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-07-29 00:00:00 -> rows=1694

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.08.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.08.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-08-05 00:00:00 -> rows=1612

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.08.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.08.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-08-12 00:00:00 -> rows=1809

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.08.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.08.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-08-19 00:00:00 -> rows=1965

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.08.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.08.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-08-26 00:00:00 -> rows=2103

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.09.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.09.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-09-02 00:00:00 -> rows=1914

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.09.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.09.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-09-09 00:00:00 -> rows=2195

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.09.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.09.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-09-16 00:00:00 -> rows=2083

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.09.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.09.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-09-23 00:00:00 -> rows=1497

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.09.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.09.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-09-30 00:00:00 -> rows=1772

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.10.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.10.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-10-07 00:00:00 -> rows=2020

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.10.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.10.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-10-14 00:00:00 -> rows=2519

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.10.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.10.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-10-21 00:00:00 -> rows=1672

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.10.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.10.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-10-28 00:00:00 -> rows=1295

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.11.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.11.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-11-04 00:00:00 -> rows=1672

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.11.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.11.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-11-11 00:00:00 -> rows=1827

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.11.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.11.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-11-18 00:00:00 -> rows=2598

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.11.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.11.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-11-25 00:00:00 -> rows=1708

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.12.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.12.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-12-02 00:00:00 -> rows=1609

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.12.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.12.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-12-09 00:00:00 -> rows=1998

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.12.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.12.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-12-16 00:00:00 -> rows=2550

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.12.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2024.12.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2024-12-23 00:00:00 -> rows=1965

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2024.12.30_00:00:00_TAI/2d@1h]
Success with: hmi.sharp_cea_720s[][2024.12.30_00:00:00_TAI/2d@1h]
Chunk saved in memory: 2024-12-30 00:00:00 -> rows=452

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2024 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2024.csv
Final shape: (100009, 29)

======================================================================
FETCHING YEAR 2025
======================================================================
Trying query: hmi.sharp_cea_720s[][2025.01.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.01.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-01-01 00:00:00 -> rows=1923

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.01.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.01.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-01-08 00:00:00 -> rows=1906

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.01.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.01.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-01-15 00:00:00 -> rows=1737

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.01.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.01.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-01-22 00:00:00 -> rows=1933

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.01.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.01.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-01-29 00:00:00 -> rows=1521

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.02.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.02.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-02-05 00:00:00 -> rows=2466

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.02.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.02.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-02-12 00:00:00 -> rows=1759

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.02.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.02.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-02-19 00:00:00 -> rows=2016

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.02.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.02.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-02-26 00:00:00 -> rows=1662

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.03.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.03.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-03-05 00:00:00 -> rows=2104

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.03.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.03.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-03-12 00:00:00 -> rows=2272

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.03.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.03.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-03-19 00:00:00 -> rows=2267

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.03.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.03.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-03-26 00:00:00 -> rows=1682

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.04.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.04.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-04-02 00:00:00 -> rows=2148

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.04.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.04.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-04-09 00:00:00 -> rows=2837

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.04.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.04.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-04-16 00:00:00 -> rows=2149

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.04.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.04.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-04-23 00:00:00 -> rows=2678

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.04.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.04.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-04-30 00:00:00 -> rows=1779

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.05.07_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.05.07_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-05-07 00:00:00 -> rows=2500

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.05.14_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.05.14_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-05-14 00:00:00 -> rows=1912

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.05.21_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.05.21_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-05-21 00:00:00 -> rows=2675

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.05.28_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.05.28_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-05-28 00:00:00 -> rows=1303

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.06.04_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.06.04_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-06-04 00:00:00 -> rows=1806

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.06.11_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.06.11_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-06-11 00:00:00 -> rows=1755

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.06.18_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.06.18_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-06-18 00:00:00 -> rows=2422

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.06.25_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.06.25_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-06-25 00:00:00 -> rows=1963

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.07.02_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.07.02_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-07-02 00:00:00 -> rows=1666

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.07.09_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.07.09_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-07-09 00:00:00 -> rows=1602

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.07.16_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.07.16_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-07-16 00:00:00 -> rows=1770

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.07.23_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.07.23_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-07-23 00:00:00 -> rows=1849

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.07.30_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.07.30_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-07-30 00:00:00 -> rows=1769

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.08.06_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.08.06_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-08-06 00:00:00 -> rows=1743

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.08.13_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.08.13_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-08-13 00:00:00 -> rows=1984

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.08.20_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.08.20_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-08-20 00:00:00 -> rows=2319

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.08.27_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.08.27_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-08-27 00:00:00 -> rows=1998

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.09.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.09.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-09-03 00:00:00 -> rows=1837

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.09.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.09.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-09-10 00:00:00 -> rows=1626

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.09.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.09.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-09-17 00:00:00 -> rows=1808

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.09.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.09.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-09-24 00:00:00 -> rows=1667

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.10.01_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.10.01_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-10-01 00:00:00 -> rows=1754

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.10.08_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.10.08_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-10-08 00:00:00 -> rows=1478

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.10.15_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.10.15_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-10-15 00:00:00 -> rows=1983

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.10.22_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.10.22_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-10-22 00:00:00 -> rows=2501

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.10.29_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.10.29_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-10-29 00:00:00 -> rows=2091

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.11.05_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.11.05_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-11-05 00:00:00 -> rows=1118

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.11.12_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.11.12_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-11-12 00:00:00 -> rows=1859

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.11.19_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.11.19_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-11-19 00:00:00 -> rows=2526

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.11.26_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.11.26_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-11-26 00:00:00 -> rows=1770

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.12.03_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.12.03_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-12-03 00:00:00 -> rows=1772

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.12.10_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.12.10_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-12-10 00:00:00 -> rows=1909

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.12.17_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.12.17_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-12-17 00:00:00 -> rows=1601

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.12.24_00:00:00_TAI/7d@1h]
Success with: hmi.sharp_cea_720s[][2025.12.24_00:00:00_TAI/7d@1h]
Chunk saved in memory: 2025-12-24 00:00:00 -> rows=1457

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Trying query: hmi.sharp_cea_720s[][2025.12.31_00:00:00_TAI/1d@1h]
Success with: hmi.sharp_cea_720s[][2025.12.31_00:00:00_TAI/1d@1h]
Chunk saved in memory: 2025-12-31 00:00:00 -> rows=265

/tmp/ipykernel_6771/316768405.py:41: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

Saved year 2025 to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/hmi_hourly_sharp_2025.csv
Final shape: (100897, 29)

DONE.
{2010: (21452, 29), 2011: (62145, 29), 2012: (68486, 29), 2013: (81875, 29), 2014: (88063, 29), 2015: (75981, 29), 2016: (16388, 29), 2017: (15558, 29), 2018: (7866, 29), 2019: (4917, 29), 2020: (9883, 29), 2021: (30619, 29), 2022: (70986, 29), 2023: (103314, 29), 2024: (100009, 29), 2025: (100897, 29)}

# **Cell A — merge all hourly yearly files**

In [ ]:
import glob
import pandas as pd

files = sorted(glob.glob(f"{OUT_BASE}/hmi_hourly_sharp_*.csv"))
print("Files found:", len(files))

dfs = []
for f in files:
    d = pd.read_csv(f)
    dfs.append(d)

hourly_full = pd.concat(dfs, ignore_index=True)
hourly_full["T_REC_dt"] = pd.to_datetime(hourly_full["T_REC_dt"], errors="coerce")
hourly_full["HARPNUM"] = pd.to_numeric(hourly_full["HARPNUM"], errors="coerce").astype("Int64")
hourly_full["NOAA_AR"] = pd.to_numeric(hourly_full["NOAA_AR"], errors="coerce").astype("Int64")

hourly_full = hourly_full.dropna(subset=["T_REC_dt", "HARPNUM"]).copy()
hourly_full = hourly_full.sort_values(["HARPNUM", "T_REC_dt"]).reset_index(drop=True)

merged_out = f"{OUT_BASE}/HMI_SHARP_HOURLY_2010_2025_MERGED.csv"
hourly_full.to_csv(merged_out, index=False)

print("Merged shape:", hourly_full.shape)
print("Saved merged file to:")
print(merged_out)

Files found: 16
Merged shape: (858439, 29)
Saved merged file to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/HMI_SHARP_HOURLY_2010_2025_MERGED.csv

# **Cell B — Then build your ML-ready hourly 16-feature file**

In [ ]:
core_features = [
    "T_REC_dt", "year", "NOAA_AR",
    "MEANGBZ", "MEANGAM", "MEANGBT", "MEANGBH",
    "MEANJZD", "TOTUSJZ", "MEANALP", "MEANJZH",
    "ABSNJZH", "SAVNCPP", "MEANSHR", "SHRGT45",
    "R_VALUE", "USFLUX", "TOTPOT", "TOTUSJH"
]

available_core = [c for c in core_features if c in hourly_full.columns]
missing_core = [c for c in core_features if c not in hourly_full.columns]

print("Available core:", available_core)
print("Missing core:", missing_core)

ml16_hourly = hourly_full[available_core].copy()
ml16_hourly = ml16_hourly.sort_values(["NOAA_AR", "T_REC_dt"]).reset_index(drop=True)

ml16_out = f"{OUT_BASE}/HMI_AR_2010_2025_ML_READY_16_HOURLY.csv"
ml16_hourly.to_csv(ml16_out, index=False)

print("Saved hourly ML16 dataset to:")
print(ml16_out)
print("Shape:", ml16_hourly.shape)

Available core: ['T_REC_dt', 'year', 'NOAA_AR', 'MEANGBZ', 'MEANGAM', 'MEANGBT', 'MEANGBH', 'MEANJZD', 'TOTUSJZ', 'MEANALP', 'MEANJZH', 'ABSNJZH', 'SAVNCPP', 'MEANSHR', 'SHRGT45', 'R_VALUE', 'USFLUX', 'TOTPOT', 'TOTUSJH']
Missing core: []
Saved hourly ML16 dataset to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/HMI_AR_2010_2025_ML_READY_16_HOURLY.csv
Shape: (858439, 19)

# **Cell C — parse GOES and prepare M/X + all-flare tables**

In [ ]:
import glob
import re
import numpy as np
import pandas as pd

AR_MAIN_BASE = "/content/drive/MyDrive/AR_Stratified"
GOES_BASE = f"{AR_MAIN_BASE}/GOES_XRAY_EVENTS"

goes_files = sorted(glob.glob(f"{GOES_BASE}/GOES XRAY events for *.txt"))
print("GOES files found:", len(goes_files))

def parse_goes_line(line):
    line = line.strip()
    if not line or "Written" in line or "GOES" in line or "events" in line.lower():
        return None

    tokens = line.split()
    if len(tokens) < 4:
        return None

    if not re.match(r"^\d{1,2}-[A-Za-z]{3}-\d{4}$", tokens[0]):
        return None

    date = tokens[0]

    class_idx = None
    for i, t in enumerate(tokens):
        if re.match(r"^[A-Z][0-9](\.[0-9])?$", t):
            class_idx = i
            break

    if class_idx is None:
        return None

    start_time = tokens[1] if len(tokens) > 1 else None
    peak_time = tokens[2] if len(tokens) > 2 else None
    flare_class = tokens[class_idx]
    location = tokens[class_idx + 1] if class_idx + 1 < len(tokens) else None

    noaa_ar = np.nan
    for t in tokens[class_idx + 1:]:
        if re.fullmatch(r"\d{4,5}", t):
            noaa_ar = int(t)
            break

    return {
        "flare_date": date,
        "start_time": start_time,
        "peak_time": peak_time,
        "flare_class": flare_class,
        "location": location,
        "NOAA_AR": noaa_ar,
    }

rows = []
for file in goes_files:
    with open(file, "r", errors="ignore") as f:
        for line in f:
            parsed = parse_goes_line(line)
            if parsed is not None:
                rows.append(parsed)

goes_df = pd.DataFrame(rows)
print("Raw parsed GOES shape:", goes_df.shape)

goes_df = goes_df.dropna(subset=["flare_date", "start_time"]).copy()
goes_df["flare_start_dt"] = pd.to_datetime(
    goes_df["flare_date"] + " " + goes_df["start_time"],
    errors="coerce"
)
goes_df = goes_df.dropna(subset=["flare_start_dt"]).copy()
goes_df["NOAA_AR"] = pd.to_numeric(goes_df["NOAA_AR"], errors="coerce").astype("Int64")
goes_df["flare_class"] = goes_df["flare_class"].astype(str).str.strip()
goes_df["class_letter"] = goes_df["flare_class"].str[0]
goes_df["class_mag"] = pd.to_numeric(goes_df["flare_class"].str[1:], errors="coerce")
goes_df = goes_df.dropna(subset=["NOAA_AR", "class_letter"]).copy()

def get_flux_value(flare_class_str):
    if pd.isna(flare_class_str):
        return np.nan
    s = str(flare_class_str).strip()
    if len(s) < 2:
        return np.nan

    letter = s[0].upper()
    try:
        mag = float(s[1:])
    except ValueError:
        return np.nan

    base_map = {
        "A": 1e-8,
        "B": 1e-7,
        "C": 1e-6,
        "M": 1e-5,
        "X": 1e-4,
    }
    if letter not in base_map:
        return np.nan
    return mag * base_map[letter]

goes_df["peak_flux"] = goes_df["flare_class"].apply(get_flux_value)
goes_df["year"] = goes_df["flare_start_dt"].dt.year

goes_all = goes_df.sort_values(["NOAA_AR", "flare_start_dt"]).reset_index(drop=True)
goes_mx = goes_all[goes_all["class_letter"].isin(["M", "X"])].copy()
goes_mx = goes_mx.sort_values(["NOAA_AR", "flare_start_dt"]).reset_index(drop=True)

print("GOES all shape:", goes_all.shape)
print("GOES M/X shape:", goes_mx.shape)
display(goes_mx.head())

GOES files found: 16
Raw parsed GOES shape: (34723, 6)
GOES all shape: (27667, 11)
GOES M/X shape: (2240, 11)

,flare_date,start_time,peak_time,flare_class,location,NOAA_AR,flare_start_dt,class_letter,class_mag,peak_flux,year
0,20-Jan-2010,10:46,10:59,M1.8,S25E87,11041,2010-01-20 10:46:00,M,1.8,0.000018,2010
1,7-Feb-2010,02:20,02:34,M6.4,N21E11,11045,2010-02-07 02:20:00,M,6.4,0.000064,2010
2,8-Feb-2010,11:57,12:03,M1.1,N21W07,11045,2010-02-08 11:57:00,M,1.1,0.000011,2010
3,12-Feb-2010,11:19,11:26,M8.3,N33E13,11046,2010-02-12 11:19:00,M,8.3,0.000083,2010
4,12-Feb-2010,17:52,18:08,M1.1,N33E10,11046,2010-02-12 17:52:00,M,1.1,0.000011,2010

# **Cell D — build hourly 3H features and labels**

In [ ]:
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm

df3h = ml16_hourly.copy()

df3h["flare_count_past_3h"] = 0
df3h["time_since_last_flare_hours_3h"] = np.nan
df3h["max_peak_flux_past_3h"] = np.nan
df3h["mean_peak_flux_past_3h"] = np.nan
df3h["flare_activity_index_past_3h"] = 0.0
df3h["label_MX_3h"] = 0
df3h["future_flare_start_dt_mx3h"] = pd.NaT
df3h["had_flare_past_3h"] = 0

df3h = df3h.sort_values(["NOAA_AR", "T_REC_dt"]).reset_index(drop=True)

unique_ars = df3h["NOAA_AR"].dropna().unique()

print("Building 3H flare-history features...")
for ar_num in tqdm(unique_ars, desc="Past 3H features"):
    ar_idx = df3h.index[df3h["NOAA_AR"] == ar_num]
    goes_subset = goes_all[goes_all["NOAA_AR"] == ar_num].copy()

    if goes_subset.empty:
        continue

    flare_times = goes_subset["flare_start_dt"].values
    flare_flux = goes_subset["peak_flux"].values

    for idx in ar_idx:
        current_time = df3h.at[idx, "T_REC_dt"]
        window_start = current_time - pd.Timedelta(hours=3)

        # strictly past only: (t-3h, t)
        mask_past = (
            (flare_times > np.datetime64(window_start)) &
            (flare_times < np.datetime64(current_time))
        )

        relevant_flux = flare_flux[mask_past]
        relevant_times = flare_times[mask_past]

        df3h.at[idx, "flare_count_past_3h"] = int(mask_past.sum())

        if mask_past.sum() > 0:
            df3h.at[idx, "max_peak_flux_past_3h"] = np.nanmax(relevant_flux)
            df3h.at[idx, "mean_peak_flux_past_3h"] = np.nanmean(relevant_flux)
            df3h.at[idx, "flare_activity_index_past_3h"] = np.nansum(relevant_flux)
            last_flare_time = pd.Timestamp(relevant_times.max())
            delta_hours = (current_time - last_flare_time).total_seconds() / 3600.0
            df3h.at[idx, "time_since_last_flare_hours_3h"] = delta_hours
            df3h.at[idx, "had_flare_past_3h"] = 1

print("Applying M/X 3H future labels...")
for _, row in tqdm(goes_mx.iterrows(), total=len(goes_mx), desc="MX 3H labels"):
    ar_num = row["NOAA_AR"]
    flare_time = row["flare_start_dt"]

    start_win = flare_time - pd.Timedelta(hours=3)
    end_win = flare_time

    mask = (
        (df3h["NOAA_AR"] == ar_num) &
        (df3h["T_REC_dt"] >= start_win) &
        (df3h["T_REC_dt"] < end_win)
    )

    if mask.any():
        df3h.loc[mask, "label_MX_3h"] = 1
        df3h.loc[mask, "future_flare_start_dt_mx3h"] = flare_time

print("Done.")

Building 3H flare-history features...

Past 3H features:   0%|          | 0/2305 [00:00<?, ?it/s]

Applying M/X 3H future labels...

MX 3H labels:   0%|          | 0/2240 [00:00<?, ?it/s]

Done.

# **Cell E — save and verify the final 3H dataset**

In [ ]:
OUT_BASE = "/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY"
out_3h = f"{OUT_BASE}/HMI_AR_2010_2025_ML_READY_16_LABELED_MX3H_FLARE_FEATURES_HOURLY.csv"

df3h.to_csv(out_3h, index=False)

print("Saved 3H hourly dataset to:")
print(out_3h)
print("Shape:", df3h.shape)

print("\nLabel distribution:")
print(df3h["label_MX_3h"].value_counts(dropna=False))

print("\nPositive ratio:")
print(df3h["label_MX_3h"].value_counts(normalize=True, dropna=False))

print("\nGrouped cadence check within NOAA_AR:")
print(
    df3h.sort_values(["NOAA_AR", "T_REC_dt"])
       .groupby("NOAA_AR")["T_REC_dt"]
       .diff()
       .value_counts()
       .head(20)
)

print("\nLeakage check:")
tmp = df3h.copy()
tmp["future_flare_start_dt_mx3h"] = pd.to_datetime(tmp["future_flare_start_dt_mx3h"], errors="coerce")
leak_rows = tmp[
    (tmp["label_MX_3h"] == 1) &
    tmp["future_flare_start_dt_mx3h"].notna() &
    (tmp["future_flare_start_dt_mx3h"] <= tmp["T_REC_dt"])
]
print("Future-label leakage rows:", len(leak_rows))

display(
    df3h[
        [
            "T_REC_dt", "NOAA_AR", "label_MX_3h",
            "flare_count_past_3h", "had_flare_past_3h",
            "time_since_last_flare_hours_3h",
            "max_peak_flux_past_3h",
            "mean_peak_flux_past_3h",
            "flare_activity_index_past_3h",
            "future_flare_start_dt_mx3h"
        ]
    ].head(20)
)

Saved 3H hourly dataset to:
/content/drive/MyDrive/AR_Stratified/HMI_SHARP_HOURLY/HMI_AR_2010_2025_ML_READY_16_LABELED_MX3H_FLARE_FEATURES_HOURLY.csv
Shape: (858439, 27)

Label distribution:
label_MX_3h
0    855388
1      3051
Name: count, dtype: int64

Positive ratio:
label_MX_3h
0    0.996446
1    0.003554
Name: proportion, dtype: float64

Grouped cadence check within NOAA_AR:
T_REC_dt
0 days 01:00:00    419598
0 days 02:00:00     43189
0 days 00:00:00      7271
0 days 03:00:00      5191
0 days 05:00:00      2381
0 days 06:00:00       574
0 days 04:00:00       468
0 days 08:00:00       385
0 days 07:00:00       283
0 days 09:00:00       121
1 days 01:00:00        62
0 days 10:00:00        58
0 days 15:00:00        36
0 days 11:00:00        34
0 days 14:00:00        28
0 days 18:00:00        25
0 days 12:00:00        25
0 days 17:00:00        16
0 days 13:00:00        15
0 days 23:00:00         9
Name: count, dtype: int64

Leakage check:
Future-label leakage rows: 0

,T_REC_dt,NOAA_AR,label_MX_3h,flare_count_past_3h,had_flare_past_3h,time_since_last_flare_hours_3h,max_peak_flux_past_3h,mean_peak_flux_past_3h,flare_activity_index_past_3h,future_flare_start_dt_mx3h
0,2010-05-03 05:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
1,2010-05-03 07:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
2,2010-05-03 08:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
3,2010-05-03 09:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
4,2010-05-03 10:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
5,2010-05-03 11:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
6,2010-05-03 13:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
7,2010-05-03 14:00:00,11063,0,1,1,0.366667,1.500000e-07,1.500000e-07,1.500000e-07,NaT
8,2010-05-03 15:00:00,11063,0,1,1,1.366667,1.500000e-07,1.500000e-07,1.500000e-07,NaT
9,2010-05-03 16:00:00,11063,0,1,1,2.366667,1.500000e-07,1.500000e-07,1.500000e-07,NaT
10,2010-05-03 17:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
11,2010-05-03 20:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
12,2010-05-03 21:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
13,2010-05-03 22:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
14,2010-05-03 23:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
15,2010-05-04 01:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
16,2010-05-04 02:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
17,2010-05-04 03:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
18,2010-05-04 04:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT
19,2010-05-04 05:00:00,11063,0,0,0,NaN,NaN,NaN,0.000000e+00,NaT

In [ ]:
print(df3h.shape)
print(df3h["label_MX_3h"].value_counts())
print(df3h["label_MX_3h"].value_counts(normalize=True))
print(
    df3h.sort_values(["NOAA_AR", "T_REC_dt"])
       .groupby("NOAA_AR")["T_REC_dt"]
       .diff()
       .value_counts()
       .head(20)
)

(858439, 27)
label_MX_3h
0    855388
1      3051
Name: count, dtype: int64
label_MX_3h
0    0.996446
1    0.003554
Name: proportion, dtype: float64
T_REC_dt
0 days 01:00:00    419598
0 days 02:00:00     43189
0 days 00:00:00      7271
0 days 03:00:00      5191
0 days 05:00:00      2381
0 days 06:00:00       574
0 days 04:00:00       468
0 days 08:00:00       385
0 days 07:00:00       283
0 days 09:00:00       121
1 days 01:00:00        62
0 days 10:00:00        58
0 days 15:00:00        36
0 days 11:00:00        34
0 days 14:00:00        28
0 days 18:00:00        25
0 days 12:00:00        25
0 days 17:00:00        16
0 days 13:00:00        15
0 days 23:00:00         9
Name: count, dtype: int64